[package]
name = "updater"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
codebake = { path = "../codebake" }
serde = { version = "1.0", features = ["derive"] }
tinytemplate = "1.2.1"