name: Update Wiki

on:
  push:
    branches:
      - main
    paths:
      - codebake/src/ops/**
      - wiki-updater/**

jobs:
  Update-Wiki:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout codebake
        uses: actions/checkout@v3
        with:
          path: main
      - name: Checkout wiki
        uses: actions/checkout@v3
        with:
          repository: ${{ github.repository }}.wiki
          path: wiki
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Update wiki
        working-directory: ./main
        run: |
          cargo run --bin updater
          mv Operation-Reference.md ../wiki/Operation-Reference.md
          mv wiki-updater/push ../wiki/push
      - name: Configure git to push
        working-directory: ./wiki
        run: |
          git config --local user.email "wiki-action[bot]@users.noreply.github.com"
          git config --local user.name "wiki-action[bot]"
          git add Operation-Reference.md
          chmod +x push
          ./push
          